# Generated by Django 3.1 on 2021-03-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loan_for', models.CharField(choices=[('v', 'Vehicle'), ('m', 'Motor Bike')], default='v', max_length=5)),
                ('item_inspected', models.CharField(choices=[('v', 'Vehicle'), ('m', 'Motor Bike')], default='v', max_length=5)),
                ('make', models.CharField(max_length=70)),
                ('registration', models.CharField(max_length=30)),
                ('chasis_number', models.CharField(max_length=17)),
                ('insurance_policy_number', models.CharField(max_length=50)),
                ('insurance_starting_date', models.DateField()),
                ('insurance_expiry_date', models.DateField()),
                ('cubic_capacity', models.IntegerField()),
                ('road_worthiness_starting_date', models.DateField()),
                ('road_worthiness_expiry_date', models.DateField()),
                ('driving_license_number', models.CharField(max_length=30)),
                ('driving_license_starting_date', models.DateField()),
                ('driving_license_expiry_date', models.DateField()),
                ('deed_status', models.CharField(max_length=5, verbose_name='Deed of Assignment')),
            ],
        ),
    ]
