# Generated by Django 3.1 on 2021-03-10 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_auto_20210310_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inspection.manager'),
            preserve_default=False,
        ),
    ]
