# Generated by Django 3.1 on 2021-03-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_report_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
