# Generated by Django 3.1 on 2021-04-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
