# Generated by Django 3.1 on 2021-04-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_auto_20210406_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='after_and',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
