# Generated by Django 3.1 on 2021-06-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_report_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='driving_license_expiry_date',
            field=models.DateField(verbose_name='License Expiry/Renewal Date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='driving_license_starting_date',
            field=models.DateField(verbose_name='License Start Date'),
        ),
    ]
