# Generated by Django 3.1 on 2021-06-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0009_auto_20210601_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='taking_benefit',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='driving_license_starting_date',
            field=models.DateField(),
        ),
    ]
